apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 84
      protocol: "TCP"
      targetPort: "phpmyadmin"
  type: LoadBalancer