apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: argo-cd
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
      targetPort: 3306
  #clusterIP: None
