apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 82
      protocol: "TCP"
      targetPort: "frontend-admin"
  type: LoadBalancer