apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret
spec:
  destination:
    name: in-cluster
    namespace: argo-cd
  project: default
  source:
    repoURL: https://github.com/FastCook2/ArgoApps.git
    path: Secrets
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
