apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
spec:
  destination:
    name: in-cluster
    namespace: argo-cd
  project: default
  source:
    repoURL: https://github.com/FastCook/ArgoApps.git
    path: Apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true