apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              key: APP_NAME
              name: config-map
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              key: API_URL
              name: config-map
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              key: APP_URL
              name: config-map
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              key: APP_PORT
              name: config-map
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              key: DATABASE_HOST
              name: config-map
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              key: DATABASE_PORT
              name: config-map
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: mysql-secrets
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: mysql-secrets
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_NAME
              name: config-map
        - name: JWT_USER_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: JWT_USER_SECRET_KEY
              name: config-map
        - name: JWT_ADMIN_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: JWT_ADMIN_SECRET_KEY
              name: config-map
        - name: JWT_USER_EXPIRE_TIME
          valueFrom:
            configMapKeyRef:
              key: JWT_USER_EXPIRE_TIME
              name: config-map
        - name: JWT_ADMIN_EXPIRE_TIME
          valueFrom:
            configMapKeyRef:
              key: JWT_ADMIN_EXPIRE_TIME
              name: config-map
        - name: MAIL_MAILER
          valueFrom:
            configMapKeyRef:
              key: MAIL_MAILER
              name: config-map
        - name: MAIL_HOST
          valueFrom:
            configMapKeyRef:
              key: MAIL_HOST
              name: config-map
        - name: MAIL_PORT
          valueFrom:
            configMapKeyRef:
              key: MAIL_PORT
              name: config-map
        - name: MAIL_USERNAME
          valueFrom:
            configMapKeyRef:
              key: MAIL_USERNAME
              name: config-map
        - name: MAIL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MAIL_PASSWORD
              name: config-map
        - name: MAIL_FROM_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: MAIL_FROM_ADDRESS
              name: config-map
        image: sahakanush224/fast_cook_back:0.1.21
        name: backend
        ports:
        - containerPort: 3000
          name: backend-port
          protocol: TCP
      restartPolicy: Always
