apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - env:
        - name: REACT_APP_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: API_URL
              name: config-map
        image: sahakanush224/fast_cook_front_admin:0.1.1
        name: frontend
        ports:
        - containerPort: 3000
          name: frontend-admin
          protocol: TCP
