apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    run: backend
spec:
  selector:
    app: backend
  ports:
    - port: 81
      protocol: "TCP"
      targetPort: "backend-port"
  type: LoadBalancer