apiVersion: v1
kind: ConfigMap
metadata:
  name: "config-map"
  namespace: "argo-cd"
data:
  APP_NAME: "Fast Cook"
  APP_ENV: "dev"
  API_URL: "http://34.107.8.120"
  APP_URL: "http://34.89.174.157"
  APP_PORT: "3000"

  DATABASE_HOST: "mysql.argo-cd.svc.cluster.local"
  DATABASE_PORT: "3306"
  DATABASE_USER: "root1"
  DATABASE_PASSWORD: "root1"
  DATABASE_NAME: "fastCook"

  JWT_USER_SECRET_KEY: "user1abcd"
  JWT_ADMIN_SECRET_KEY: "admin1abcd"
  JWT_USER_EXPIRE_TIME: "50h"
  JWT_ADMIN_EXPIRE_TIME: "50h"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "fastcookpadc83@gmail.com"
  MAIL_PASSWORD: "vppezxncceluacfr"
  MAIL_FROM_ADDRESS: "fastcookpadc83@gmail.com"

  GCP_PROJECT_ID: "fast-cook-375012"
  GCP_CLIENT_EMAIL: "fast-cook@fast-cook-375012.iam.gserviceaccount.com"
  GCP_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQChIhw67cDZFwOX\nx1IlYSx9zQGrk7jX4n3863CWIHn7R+7kPdmBZe7jKL6vgSb5m+HMnAbtrjLL2LMp\nN8PDKB6guasIb7RYrEc+48dyXPgIix5z7RUVa1wzhQHR1n2mB+8LBOKKx3My1+s9\nMuLoSf46gP67/vtlBS2QnXwNdrvin1C6AiafENfkVFO8v7/rXPbEcGLasE7y+fyy\nHF4e9NB2AguQP5h6FEcJ9KmjbGt0vunA63pBYd2sFt2IPueuaM5lnrnSawEphRBR\nT7ocwI5uRhhU+S7mR8lZ3UHN75+FwkKQY65xxMIFqdvYSCi+LhIPTpHjcd/No1WV\nAiqxDw1/AgMBAAECggEAFWVK8VTg6WfsaArP8LsH+4ZYD+5+ugUkQeFeDZkvXqXi\nZeKD5JzijRLmdbXFCpo1GoRR890lzTqE2QFuGEEAsXUl7ZSuPPislysLWzdWugUF\nsf1LnOX+FAXibs4NLhmEl2Z6fFStNRWa8gE1RFnljOLUWvspv3QMulSnBGn9MG33\n+d9JxIbVxdGlGHSIqY8Rr0fbwasL8KTgBEOn7+noivP/fbyvGU0rsMKpz8IqOD4b\nWnANdabYbgJk9Jnvwx+gcyq74KNaITcmWHvX0Z8mX/RbccRjCqmjXDjXxWYjv1hA\nVUKEST316FC837ohojRBBa2hzVKnn/VkfLbKHCsI1QKBgQDfE/O20PzRGjrJckGd\n5p8TLng9Gdl0OuaKm6D/+mG54TYb7Fl7P9lnDz/o8RtvePuvP1XfH/Uw67apnH/h\nSoJpb6F+jc57o4FMGIg12cYaaQ4I8Uk9W2WpoBzp6KIcLXQf6NHDL9PyuU8xNtM/\nwDqc59W4zcvABNA3HWQvV/PQSwKBgQC46dehwdofh8PCi4RuBaHXdJBf4KLV2EJ+\ntXxd71UlIyxndSOHa/zInRo30m0+7T67bJexWY4ISit3ndxD+Zd1fDLFWZHiTkYv\ngBF4Kr+oF43j1l0LX/tR2l6wzKr5emaSUeZGDGrPuz2raAmd+yUYAlUOhMqPUcAE\nv3edvco/HQKBgHewgdP1/5/FvgL1vcUVxwYIqdTGuMjHDYkTBWgylBqifmCvCDe7\nw06rfPPj4X+G3ythBRbpU6oC3ofUgzyCuMQPdAut1Dq8OJR2mSajiMoE0dX0eAJm\ntn4zfS/3dHs/3A1+4oUidUrHKHlUXDXZUtl6/k3ghVCqhHj92RIZ06RPAoGAH3Ic\n6nQ17NDAuK/TOIaarDI1byibaHRbcoLYgHz35NXjckCYZyo1FcSptb6CN4ZO+b6Q\n2WcaYUyDsdbVo3WpjSAu3iLKTUr0YpWL4vyaFTLUPV+x+QI8kgHpwnU7yitHkDB/\nUYBBFcyIw0JxCD2yZC/ZWRu5+r9zQRtycw/Yef0CgYEA1BPuKcXSo3DiOz4aXmVl\nXenaxR8er/10vDe71bjxMr1zl5y95T6k+JvdE2BEO5eWmz1h7QkxaL4C1HIIQiGg\nOxw6ivAnYFNW3RejzflhboqmyMaeJ1XzTN5MfRoGUAkBXGt/Jqq2yuGq0pWXeLSd\ns/t7cscpJXz7tpIN+buqc9o=\n-----END PRIVATE KEY-----\n"
  GCP_BUCKET: "storage-bucket-24"